package com.fernan2529.Novelas;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.Spinner;

import androidx.appcompat.app.AppCompatActivity;

import com.fernan2529.R;
import com.fernan2529.WebViewActivities.WebViewActivityGeneral;

import java.util.Random;

public class novelas1 extends AppCompatActivity {

    private Spinner spinnerVideos;
    private ArrayAdapter<String> videosAdapter;
    private Random random;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_novelas1);

        spinnerVideos = findViewById(R.id.spinner_videos);
        Button playRandomButton = findViewById(R.id.aleatorio);

        // Nombres visibles en el Spinner
        final String[] videoNames = {
                "Seleccione el Capitulo",
                "1. Analogías",
                "2. Nuevo ingreso",
                "3. Atracción inevitable",
                "4. El tiro por la culata",
                "5. La infamia de la verdad",
                "6. Celos y envidia",
                "7. El segundo anónimo",
                "8. La ley del más fuerte",
                "9. Defender la dignidad",
                "10. Ladrona",
                "11. Soborno",
                "12. Presunto acoso",
                "13. El novio",
                "14. El comienzo de la venganza",
                "15. Engaños",
                "16. El beso",
                "17. La marca de la logia",
                "18. Traicionar la amistad",
                "19. Amenazas",
                "20. Beso inesperado",
                "21. Baile sensual",
                "22. Mentiras",
                "23. Mala amiga",
                "24. Baile espectacular",
                "25. Amistad terminada",
                "26. Un corazón roto",
                "27. Huelga",
                "28. Terapia inconclusa",
                "29. Enfermeros",
                "30. Un nuevo estudiante",
                "31. Cita arruinada",
                "32. Falsas esperanzas",
                "33. Engaños amorosos",
                "34. Triángulo amoroso",
                "35. Ayuda",
                "36. Momentos inolvidables",
                "37. Verdad a la luz",
                "38. Interés",
                "39. Gran escape",
                "40. Gran problema",
                "41. Clase inesperada",
                "42. Asesino",
                "43. Traición",
                "44. Dura realidad",
                "45. Plan de emergencia",
                "46. Nuevo noviazgo",
                "47. Reclamos",
                "48. Autosecuestro",
                "49. Nuevo grupo",
                "50. Divorcio",
                "51. En las calles",
                "52. Expulsión",
                "53. Discusiones",
                "54. Un nuevo compromiso",
                "55. El nacimiento de una banda",
                "56. Gran sorpresa",
                "57. Pretendiendo",
                "58. Mentira piadosa",
                "59. Foto comprometedora",
                "60. Grave enfermedad",
                "61. Momentos inolvidables",
                "62. Triste Navidad",
                "63. Diferencias sociales",
                "64. Difícil decisión",
                "65. Verdadera identidad",
                "66. Viaje de fin de año",
                "67. Gran viaje",
                "68. Año nuevo de amor",
                "69. Dulce visita",
                "70. Favores",
                "71. Entre búsqueda y mentiras",
                "72. Sospechas",
                "73. Corazón roto",
                "74. Falta de amor",
                "75. Sufrimiento",
                "76. Amor a medias",
                "77. Negación",
                "78. Nuevo comienzo",
                "79. Renuncia inesperada",
                "80. Ensayo de la banda",
                "81. Confesión de amor",
                "82. Fin a la relación",
                "83. Triste despedida",
                "84. Seducción",
                "85. Traiciones",
                "86. Falsa identidad",
                "87. Dolorosa verdad",
                "88. Trampas",
                "89. Amor de madre",
                "90. Amor en confesión",
                "91. La mamá de Giovanni",
                "92. Amor al descubierto",
                "93. Cita con la de la cafetería",
                "94. Plan para desenmascarar",
                "95. Verdad por confesar",
                "96. Abandono",
                "97. Pruebas",
                "98. Un buen regalo",
                "99. El diario",
                "100. Confrontación",
                "101. Triste pasado",
                "102. De regreso a casa",
                "103. Relación al descubierto",
                "104. Sentimientos encontrados",
                "105. Amor prohibido",
                "106. Celos entre compañeras",
                "107. Decepciónes",
                "108. Un nuevo amor",
                "109. Sobre aviso",
                "110. Fuera de la Banda",
                "111. Chismes",
                "112. Cubriendo apariencias",
                "113. Atrapado",
                "114. Cantando con el alma",
                "115. El hijo verdadero",
                "116. Secreto importante",
                "117. Venganza",
                "118. Otra relación",
                "119. Triste confesión",
                "120. Engaño de una hija",
                "121. Verdaderas intenciones",
                "122. El disco",
                "123. La oveja negra",
                "124. Encubridores",
                "125. La indiscreta",
                "126. Nace RBD",
                "127. Presentación en televisión",
                "128. Amigos",
                "129. La busqueda",
                "130. Tranquilidad",
                "131. Peligro de separación",
                "132. El enamorado",
                "133. Diego le confiesa a su mamá que la mujer que ama es Paola",
                "134. La nueva maestra",
                "135. Oscuras intenciones",
                "136. La modelo",
                "137. Escapando juntos",
                "138. Robos misteriosos",
                "139. Romance prohibido",
                "140. Modelo al descubierto",
                "141. Ilusiones",
                "142. Extraña relación",
                "143. Otro tipo de mujer",
                "144. Padres contratados",
                "145. La decisión de Celina",
                "146. Cubriendo espaldas",
                "147. Sinceridad",
                "148. En peligro",
                "149. Captura y Tortura",
                "150. La pelea",
                "151. En riesgo",
                "152. El traidor",
                "153. Los secretos de La Logia",
                "154. Consecuencias",
                "155. El acuerdo",
                "156. La logia se cae",
                "157. Falsificación",
                "158. Ella es mi novia",
                "159. Mujeres en baño de hombres",
                "160. La escuela en Canadá",
                "161. Duelo de besos",
                "162. Un amor separado",
                "163. Besos robados",
                "164. Amor interrumpido",
                "165. Falsas acusaciones",
                "166. Justicia",
                "167. Amor maternal",
                "168. Momentos vergonzosos",
                "169. Él reprobará",
                "170. Adivina quién",
                "171. Investigación propia",
                "172. La trampa",
                "173. Sin memoria",
                "174. Fiesta para dos",
                "175. La novia de Diego",
                "176. El secuestro",
                "177. Presentación en la cafetería",
                "178. Sorpresas de cumpleaños",
                "179. La apuesta",
                "180. Desilución",
                "181. Probando resistencias",
                "182. Novios mayores",
                "183. Mi verdadero yo",
                "184. Reencontrando el amor",
                "185. Aliados",
                "186. Ladrona de exámenes",
                "187. Beso de amor",
                "188. Carta misteriosa",
                "189. Acuerdos sorpresas",
                "190. Complot",
                "191. Maldades",
                "192. Duelo de divas",
                "193. La disculpa",
                "194. El día de la fiesta",
                "195. Volviendo a amar",
                "196. Expresando sentimientos",
                "197. Miedo a enamorarme",
                "198. Cambiando de padres",
                "199. La verdad sobre Miguel",
                "200. Indecisión",
                "201. El problema de Celina",
                "202. RBD al descubierto",
                "203. La venganza de Gastón",
                "204. El verdadero responsable",
                "205. El sufrimiento de Miguel",
                "206. Lejos de la verdad",
                "207. Propuesta inesperada",
                "208. Doble cara",
                "209. La boda",
                "210. La humillación",
                "211. Traidor",
                "212. Prueba gráfica",
                "213. El amor es lo más importante",
                "214. El destino lo arregla todo",
                "215. Buen viaje",
                "216. Media hermana",
                "217. Impulsivamente",
                "218. Cenizas de amor",
                "219. Nuevo año, nuevos retos",
                "220. El soplón",
                "221. Boda trágica",
                "222. Playa encantada",
                "223. El castigo",
                "224. Testimonio",
                "225. Concierto privado",
                "226. Nueva novia",
                "227. Terrible trampa",
                "228. Falso amigo",
                "229. ¿Dónde será el ensayo?",
                "230. Fuera de la escuela",
                "231. Dilema",
                "232. Reunión",
                "233. Nuevo trabajo",
                "234. Altruismo",
                "235. Fotografías inapropiadas",
                "236. Mala persona",
                "237. Reconciliación planeada",
                "238. Injusticia",
                "239. El perdón",
                "240. Celos incontrolables",
                "241. Las apariencias engañan",
                "242. Una cuestión de confianza",
                "243. Plan malévolo",
                "244. Amor incierto",
                "245. La víctima",
                "246. No todo es lo que parece",
                "247. Precampañas",
                "248. Campaña desleal",
                "249. Secuestrado",
                "250. La petición de rescate",
                "251. Autor intelectual",
                "252. Falsa empatía",
                "253. Interesada",
                "254. Aunque te pierda",
                "255. Confianza",
                "256. La rifa",
                "257. Interrogatorio",
                "258. Fuera de la campaña",
                "259. La nueva modelo",
                "260. Nueva presidenta",
                "261. Escape fallido",
                "262. Terrible accidente",
                "263. Visita inesperada",
                "264. Fraude",
                "265. Falsa relación",
                "266. Terrible mentira",
                "267. La fiesta de Diego",
                "268. Celos de Gastón",
                "269. Encuentro inesperado",
                "270. Amor de padre",
                "271. Obligaciones",
                "272. Acciones injustas",
                "273. Malentendido",
                "274. Engaño descubierto",
                "275. Junto a ella",
                "276. Afuera llueve",
                "277. Mentiras piadosas",
                "278. Padre estricto",
                "279. El fraude",
                "280. Cuidando a Miguel",
                "281. El ladrón de la pluma",
                "282. El desfile",
                "283. Sueño de amor",
                "284. Amigas de nuevo",
                "285. Desconfianza",
                "286. Beso peligroso",
                "287. La mejor compañía",
                "288. Visita al hospital",
                "289. Gran ayuda",
                "290. Grandes consejos",
                "291. Nuevas experiencias",
                "292. Una nueva banda",
                "293. Una nueva vocalista",
                "294. Pruebas de amor",
                "295. Corazones destruidos",
                "296. Vida interesante",
                "297. Verdad descubierta",
                "298. La venganza",
                "299. La huida",
                "300. El plan de Mía",
                "301. El gran día",
                "302. Inseguridades",
                "303. Viaje a París",
                "304. El concierto RBD",
                "305. Emocionados",
                "306. La carta",
                "307. Reclamo inesperado",
                "308. Mala relación",
                "309. Desnudos",
                "310. Amigo desplazado",
                "311. Dinero prestado",
                "312. Madre desesperada",
                "313. Amor del pasado",
                "314. Madre insoportable",
                "315. Importante entrevista",
                "316. Importante entrevista",
                "317. Pelea por amor",
                "318. Mentira descubierta",
                "319. Un buen plan",
                "320. Lugar secreto",
                "321. Nuevo novio",
                "322. Importantes apuntes",
                "323. Amistad en peligro",
                "324. Ropa cara",
                "325. Malos entendidos",
                "326. Enfrentamiento",
                "327. Caridad",
                "328. Secretos entre amigas",
                "329. Las argucias de Sol",
                "330. Protesta estudiantil",
                "331. Relación estancada",
                "332. Beso robado",
                "333. Crisis nerviosa",
                "334. Regreso inesperado y navideño",
                "335. Fiestas navideñas",
                "336. Obedeciendo órdenes",
                "337. El peor secreto",
                "338. Reclamos de amor",
                "339. Espía anónimo",
                "340. Borracha por amor",
                "341. Fiesta de año nuevo",
                "342. Regalos del corazón",
                "343. Rivalidades",
                "344. Descubrimientos inesperados",
                "345. Segundas oportunidades",
                "346. Amor innegable",
                "347. Sacrificios",
                "348. Ampliación del negocio",
                "349. La verdadera historia",
                "350. Enredos",
                "351. Aprovechar las oportunidades",
                "352. Amor compartido",
                "353. Estoy lista",
                "354. Capitanas del equipo",
                "355. Visita al médico",
                "356. Hija adoptiva",
                "357. Fotografías reveladoras",
                "358. Grave pelea",
                "359. Alianzas peligrosas",
                "360. Delitos ocultos",
                "361. Anónimo",
                "362. Petición de divorcio",
                "363. Lo sé todo",
                "364. Noticias sobre mamá",
                "365. La gran fiesta",
                "366. Jugadas sucias",
                "367. Déjame solo",
                "368. Torneo de fútbol",
                "369. La verdadera novia",
                "370. Hermanastro insoportable",
                "371. Padres divorciados",
                "372. Fuera del torneo",
                "373. Noche romántica",
                "374. De regreso al torneo",
                "375. Heridas del partido",
                "376. Remordimiento de consciencia",
                "377. Embarazo inesperado",
                "378. Rumor en el colegio",
                "379. Planeando un viaje",
                "380. Padre biológico",
                "381. La burla del colegio",
                "382. La reconciliación",
                "383. La gira arranca",
                "384. Profesores en descanso",
                "385. Linda reconciliación",
                "386. Sin ganas de cantar",
                "387. En el hotel",
                "388. Miedo a morir",
                "389. Disfrutando la playa",
                "390. Fiesta en la playa",
                "391. Espiando a su ex novia",
                "392. Atracción mutua",
                "393. Declaración de amor",
                "394. Serenata de amor",
                "395. Reconciliación",
                "396. Defendiendo al profesor",
                "397. Madre sin amor",
                "398. En el hospital",
                "399. Cámara oculta",
                "400. Otro colegio",
                "401. Renuncia por amor",
                "402. La huida",
                "403. Verdad dolorosa",
                "404. La verdad sobre su origen",
                "405. La maldad de Gastón",
                "406. El retorno",
                "407. La ira de Gastón",
                "408. Accidente fatal",
                "409. Una gran noticia",
                "410. Profunda tristeza",
                "411. Decisiones",
                "412. Buenas noticias",
                "413. Sin padre",
                "414. Tristeza infinita",
                "415. Felicidad incompleta",
                "416. La gira",
                "417. Siendo honesto",
                "418. La carta del tutor",
                "419. Palabras verdaderas",
                "420. Avergonzada",
                "421. Sin amor materno",
                "422. La confesión de Roberta",
                "423. En riesgo de muerte",
                "424. La venganza de León",
                "425. La revancha",
                "426. El intercambio",
                "427. Vida olvidada",
                "428. Pérdida de memoria",
                "429. La prueba de embarazo",
                "430. Embarazo al descubierto",
                "431. Sola y con un hijo",
                "432. Confusión de nombres",
                "433. La mentira de Franco",
                "434. Tratando de recordar",
                "435. Conociendo a mamá",
                "436. Como amigos",
                "437. Enfrentamiento madre e hija",
                "438. Patria potestad",
                "439. Amor por siempre",
                "440. Sé rebelde"


        };

        // URLs correspondientes (mismo índice que videoNames)
        final String[] videoUrls = {
                "",
                "https://drive.google.com/file/d/173vesUFd1iwHyT3Zzpb0nAaGP5I7NjUR/view",
                "https://drive.google.com/file/d/1KT0gocAI2wmpis1ejAtMIjBEQp0uxoQ8/view",
                "https://drive.google.com/file/d/1keYFc27Fl9ZcRO9VzsQz4U1J-u8AU7el/view",
                "https://drive.google.com/file/d/1yyNn3G7vemSIpJmSaUa6Tbct0wzB4-Qm/view",
                "https://drive.google.com/file/d/1dMXi-tRY9obbRyeNVbtSyJR5V4elHklC/view",
                "https://drive.google.com/file/d/1vxkVrwHwKgU5FdkqyVGQlnFUqvYB4z6l/view",
                "https://drive.google.com/file/d/1QabC5T9SwI4NY0J8LmZPxRJtcVcu1rxC/view",
                "https://drive.google.com/file/d/1znqOEMS0O_KJ2k8VPJLPQ2EasKEZbmvC/view",
                "https://drive.google.com/file/d/144mhG1tlmfds46Xww5PZ9z5HK6WCV2vk/view",
                "https://drive.google.com/file/d/1tVCarBpjjabFu1FClIkLFYEVx06RtjrO/view",
                "https://drive.google.com/file/d/1GsMddZ3o5WghM8X_rrZHSSF1-lubGE7v/view",
                "https://drive.google.com/file/d/1VtnbjEn9WEhJvbDLkufniBeyEBBlqIyQ/view",
                "https://drive.google.com/file/d/1azY_A4rPG8JX0y-OX52SazwBKqA5hXSH/view",
                "https://drive.google.com/file/d/1lr9gHBB3wqDwwcKCAIc-rZxdYOzpJehO/view",
                "https://drive.google.com/file/d/1j6rErzGg2h7kvkGY1cyO4fAUSWlIMZXm/view",
                "https://drive.google.com/file/d/1B6rEYAYRnE-OXaw96X7K2hU7YfWEkt0Z/view",
                "https://drive.google.com/file/d/16QFhME63Vw5st-i-xEno3skU0aDIfaOX/view",
                "https://drive.google.com/file/d/139KAyVKbFEVSMsDG_opnJN0S8_IEeocd/view",
                "https://drive.google.com/file/d/1WoHUm5pjbvFcK6S4s0i0z3DqkEv7OLcT/view",
                "https://drive.google.com/file/d/1ec0M4aniHwBpOaLrBo7ygKmiLbcxQhGP/view",
                "https://drive.google.com/file/d/1G07V9uG-yS_I4z-iRq5UaKMwdowIhKMU/view",
                "https://drive.google.com/file/d/1sFJqKuwso83hvWlgU8NVUmCFsW_D1dnI/view",
                "https://drive.google.com/file/d/1DD5-Sf78lyKDtfnYQrExsDtJvMbBjiTl/view",
                "https://drive.google.com/file/d/1gKhrHBZy0A8GV7ElPIr1pObiFU3C4T2q/view",
                "https://drive.google.com/file/d/1r3lvvdtrgZUt03vLutwKjrAf9Cas1Xwo/view",
                "https://drive.google.com/file/d/1nbfPjFMU_MUrXX9NAv2bFTWPzpRDT9Te/view",
                "https://drive.google.com/file/d/1vEhwdoA_Ya31GVdf0gdZaoBz0mSlatSv/view",
                "https://drive.google.com/file/d/1Zrh-Fck97Br-XoxynyIxqtXlOQTx8gTE/view",
                "https://drive.google.com/file/d/1yq2reE_A4WI_9MkjUlar3zRj1VJMWl41/view",
                "https://drive.google.com/file/d/1IFk83BmicE4VbCen4XZmPNba9F2XvUfS/view",
                "https://drive.google.com/file/d/1cUwtEuKvW4sOl0lzgS8zOn69j9qCSjXC/view",
                "https://drive.google.com/file/d/15TqjSHWkqbgVPMqDQy2dmonYeCewNjYI/view",
                "https://drive.google.com/file/d/1zoe9QML7jGndBiLEGQGQpit5l68WuM-D/view",
                "https://drive.google.com/file/d/19BF6rhwjlvY-8tVMh-_bfKHx8Q4lnRYn/view",
                "https://drive.google.com/file/d/1ZZb7R2120XLAMCRCroZ7zS-yV6mJbZln/view",
                "https://drive.google.com/file/d/1qRhYogbad9DGZLBfKdRLGinG0tt355Qz/view",
                "https://drive.google.com/file/d/1GwWa18fOaYAGoAuamTsHgNunUB4wO-Gv/view",
                "https://drive.google.com/file/d/1FukqrvEuIAq-awqucueFuJt3e6VXbSv7/view",
                "https://drive.google.com/file/d/1DS73epxPiKEQwsXOrtsnEgEY-eRWNZZj/view",
                "https://drive.google.com/file/d/1N2AaNAGgOEB00_frFRHdglVz8y7uaMpS/view",
                "https://drive.google.com/file/d/14OEptlbCl07LV4nRKAyWXcuJm3gFASYV/view",
                "https://drive.google.com/file/d/1HqPY8VrBipwZ6uUxjqNvKbVJFS2SR1HD/view",
                "https://drive.google.com/file/d/18NLyVJArAzLr9JxIbwnWQm1JbAd8H6-d/view",
                "https://drive.google.com/file/d/1QI5o2T78O3fVwlUIhsqt0CCUqGOlFfLK/view",
                "https://drive.google.com/file/d/1T1s2wXOFG7HOkqANIOQYQAUSBUhhSl_t/view",
                "https://drive.google.com/file/d/1K1BNidqKl4Rbr93EmAyHVd5TZfEqfB-d/view",
                "https://drive.google.com/file/d/1V-sPEHrXVpPuGTXgrVPURwwEa2J5C46v/view",
                "https://drive.google.com/file/d/1pfNFC6i1MwLU9DdafWc961VK2oqMtLDs/view",
                "https://drive.google.com/file/d/1o-G2DByhAOV_pzdy8w_AMk2bUE4taG4H/view",
                "https://drive.google.com/file/d/1q6Razb-ryBHwdULxAQRc5bN7BkjqfSNo/view",
                "https://drive.google.com/file/d/18SskedWD_wOzAMBEcQPFff3B7ifbuIhH/view",
                "https://drive.google.com/file/d/1i23WHXbjJDFJszwQpfblQY4jXFAeCYmo/view",
                "https://drive.google.com/file/d/1eNb9Hbig-9-sSzTJVOu4ktuNWfIbo-Cr/view",
                "https://drive.google.com/file/d/1d45UnxCEuG2h1TjvurGTE4ArILIZ8glV/view",
                "https://drive.google.com/file/d/1XFSviTMREkOWeD6LH9Ufy2VxpkkwNdFY/view",
                "https://drive.google.com/file/d/1x_uvU9wz4UOnYZdAAX0n25J4Q0DQa_5J/view",
                "https://drive.google.com/file/d/1TPw2K0vmMBZtEesOHYYWPPjPHBXD8hzt/view",
                "https://drive.google.com/file/d/1jMMMw0EfVI_XG2_RytLxC8cckrq5zEUd/view",
                "https://drive.google.com/file/d/1CPrH_d3EHGCaavcYTcFqVrx_WLKo6jo5/view",
                "https://drive.google.com/file/d/1y29TiV9WiCS2aUMeKJjnlzzF3uphHy6u/view",
                "https://drive.google.com/file/d/1ITt7FADWJHjPqULDSqIY1v-5sEMTBJak/view",
                "https://drive.google.com/file/d/1eNkHV-uTJMdwbCeyDimuh9QmBg4mQU54/view",
                "https://drive.google.com/file/d/17zrg42Da6Eu2x7_s8x2qPTtMXsKGW4ir/view",
                "https://drive.google.com/file/d/1yRAtclVm-26S1rdSbnoEjbkJSrlCogJG/view",
                "https://drive.google.com/file/d/1LKCHmb0AmQoWy2dkTtBqmKEeXzxuMp9m/view",
                "https://drive.google.com/file/d/15eFtu2FpNmLQM6WywFUFqFy6ND4nOzKN/view",
                "https://drive.google.com/file/d/1o8bxu5ODm6AUBdCwD2Y3nH6f-72sGyLl/view",
                "https://drive.google.com/file/d/1kyIBnNCuruqH_ZAbGDxvq7oPMInex8z1/view",
                "https://drive.google.com/file/d/1WnDe6Mx3gbDI7DkWKbdsnBl2zs-szk1T/view",
                "https://drive.google.com/file/d/1m9Ad5i8iu7HuibtModsK4yGJUPDUplYX/view",
                "https://drive.google.com/file/d/1ij7VCPJ-nZnDXwbOdX6E2yGsK2oBE-MM/view",
                "https://drive.google.com/file/d/1Te3VDYpAM8RA0mwZDWfWzcz6N8OSIBWo/view",
                "https://drive.google.com/file/d/1m7nteddhNwCrCXZ_QTWr2tA3mWuJDm2T/view",
                "https://drive.google.com/file/d/1hTjEM302JLuUt3-ZjSs38kDAI62EHHHr/view",
                "https://drive.google.com/file/d/145YqP7EyrJQw8XCQv9wUySvKsBKt1Duz/view",
                "https://drive.google.com/file/d/1tYDUXPhX0Qz2W_DsQeAJjb-pVUMZyxwN/view",
                "https://drive.google.com/file/d/1D41nfHXivG_ZVTP1AHvfnL5_svvHUxAw/view",
                "https://drive.google.com/file/d/13emcmlYsd8QW5fJjVg_rmhPipqAVGkX-/view",
                "https://drive.google.com/file/d/1m0ezW1AXv9Do5PzlQeKk_AyY2xhw75tk/view",
                "https://drive.google.com/file/d/122cVTGMsWC91BVSRvepyi_cmJ--8pXKr/view",
                "https://drive.google.com/file/d/1iswgp5ZAGaLSRiCc2mlpa21AWTn_sOFE/view",
                "https://drive.google.com/file/d/1E-iQ8ye8i6WoAgBecycVEpOgZD-r4Umf/view",
                "https://drive.google.com/file/d/1E5YbFzGJWiVyyyTZPRmPkNYHl_3Nud1D/view",
                "https://drive.google.com/file/d/1A7bu3eapOuuPKYf6-KpTEJavbtn0aoN4/view",
                "https://drive.google.com/file/d/1A7bu3eapOuuPKYf6-KpTEJavbtn0aoN4/view",
                "https://drive.google.com/file/d/1VaMhG2veVYwSoyb506wgojwG3e9IRfrb/view",
                "https://drive.google.com/file/d/1cyxnrXsEyUYUeoHUA5S5fgWm-8wdDQCd/view",
                "https://drive.google.com/file/d/18W_z5srVU_hP39V7jyepxHGcKuf4e2zI/view",
                "https://drive.google.com/file/d/1Cw4laVNj1hvpPZvi2RCE8FvaE7e3XuLz/view",
                "https://drive.google.com/file/d/12VQdXj3YZcbLxh_ZI1JnyGvkYinlPB3S/view",
                "https://drive.google.com/file/d/1l5ZeJJufyDZULcd_I_KRTtmzXu9jiTHe/view",
                "https://drive.google.com/file/d/1_9opML2643jFOIDl987IUGDgYicWGgMf/view",
                "https://drive.google.com/file/d/1BD5NgEZjPUyeYCIgdVQSWnkZGh71TaFw/view",
                "https://drive.google.com/file/d/1SXt4gYwUwk6Uz4o1BbVnHftw0s_frh-O/view",
                "https://drive.google.com/file/d/1M9-6fGCCR04HFPza-86oTIJVgcBJ3Wtq/view",
                "https://drive.google.com/file/d/1UVuC6HI05ME36sgxumWb7AVLUtiTL3x8/view",
                "https://drive.google.com/file/d/1gxHYuCRo1q7LxGy4TNlSEQBaT8BBNGPl/view",
                "https://drive.google.com/file/d/1VfmDup3hHbGxUoG4f2NefLS9vcl3aIRr/view",
                "https://drive.google.com/file/d/1pQwOc-Ylpn_8ChcMoOUss85W0uHbn45t/view",
                "https://drive.google.com/file/d/1PP2-FlwH_jOSWqcuBTWtvbCWDzAdDRbr/view",

                "https://drive.google.com/file/d/16RTcrrRmI80RZV30KCPCe0bk3ZXOUYtn/view",
                "https://drive.google.com/file/d/1M9SQqsnswtZ9TbukPE2NtSg5tbqpd2-a/view",
                "https://drive.google.com/file/d/17JvNPMzLNNynS1LOcTqpMg8_YrcbvnWO/view",
                "https://drive.google.com/file/d/1G6d4rMc2A1qpoDXlBhY1S8sN8JsQn9qk/view",
                "https://drive.google.com/file/d/1M-NeKOOT48ch4TiJOZ7SRdY0xG1rm7Hy/view",
                "https://drive.google.com/file/d/18ctb2TscxlH7x-6WxMhdfMDZfWImqOQG/view",
                "https://drive.google.com/file/d/14l4LuHiQ4ZVXRNWnifC0Bv9NZCV4ME9X/view",
                "https://drive.google.com/file/d/130OWg9mjwYltYYP3lnucrYZTma622mkj/view",
                "https://drive.google.com/file/d/10bBL9CUf35l_hQr2dehDsC0oW_QecrnW/view",
                "https://drive.google.com/file/d/1MSQ8jF67FpYsWx1jDmJ7hyOqjtK4gTQf/view",
                "https://drive.google.com/file/d/1ZXBojM1wjw2FMM7He5fzx5cc0lEDb_vK/view",
                "https://drive.google.com/file/d/1_DkYgwPIDbqiajxlqxuYDwZ98rbMTGgw/view",
                "https://drive.google.com/file/d/1liAU2xfqc70JCwST8b4GKhdXPUpa3cPB/view",
                "https://drive.google.com/file/d/12pfygR8RS6QvD_KR4woHUi3DjgIqDIbA/view",
                "https://drive.google.com/file/d/1hdnGr_-iqgw2T8h6TjQXauhJqfcnfznc/view",
                "https://drive.google.com/file/d/1JQTnxl-6tB2OhnE-gwLHb9ZTuW_nkOiq/view",
                "https://drive.google.com/file/d/1VZDJnEGm-kQeSavp3uRoa2XOfR-3QqJx/view",
                "https://drive.google.com/file/d/1poQDGHueX6wa247NK1JoGV_t-suJM--G/view",
                "https://drive.google.com/file/d/1Rhux_quIhooxrANSwZAGWpUspiyTO9S0/view",
                "https://drive.google.com/file/d/1T55VzHmpQ0-0pDLaWM5WszhYWKqXUrHc/view",
                "https://drive.google.com/file/d/1jrbcOb4feMvoObM5EF78QsojjLuIiAEB/view",
                "https://drive.google.com/file/d/1_i19m9LtElkoLukJeSzGBH58dwZU5UnN/view",
                "https://drive.google.com/file/d/1gLGSJz09t3eo287cwHJ3U7IreQUbMOmC/view",
                "https://drive.google.com/file/d/1WpTzNx6zhnP4U8xByRcmGqYz4vaLUxUT/view",
                "https://drive.google.com/file/d/1ywvMakNnk2M8427bBDT_cY1zNlX2UcVR/view",
                "https://drive.google.com/file/d/1CYbRK1tL-4diGBO5gOD6dyTJPUc4GdSa/view",
                "https://drive.google.com/file/d/1EHJZYsNyvjwyK4slLdbeFs5eoZ9-lRtg/view",
                "https://drive.google.com/file/d/1A5Ne0fd-pewBRArbJ13wWwyEF-4jNd22/view",
                "https://drive.google.com/file/d/1Pqne_rTnKdRYUoQtdqkluCs3p0mDiemF/view",
                "https://drive.google.com/file/d/1WEaUJI9wF9JRh_smTXBff1mg1pBWc88y/view",
                "https://drive.google.com/file/d/1s5GxG0SfsFf8rghjE9ZQl6WvqPBKg2k0/view",
                "https://drive.google.com/file/d/16yJ07fNxvmuD6sBfghBtWQCajnApuQu3/view",
                "https://drive.google.com/file/d/1gEHV4EgXLwPPTKkZ1MwQdO74wXHsH5IK/view",
                "https://drive.google.com/file/d/1H182y7aDQKVEC3u8GRsKIgdi9YuPnEGS/view",
                "https://drive.google.com/file/d/1mefFH8_zyGxyctfLS38Bz34sJ4_UDOVx/view",
                "https://drive.google.com/file/d/1jVH6H1HcQ8XzQtT7mchBIojVDeF7_igW/view",
                "https://drive.google.com/file/d/1-zwY1o13sOnT55KokcwholByibevQCdT/view",
                "https://drive.google.com/file/d/1sAHPxmoFHEanJo2cMqdKk1IE8yLtum2Q/view",
                "https://drive.google.com/file/d/1BAZhTGXcvlFGWjRJ1QptuZFii3kabCGu/view",
                "https://drive.google.com/file/d/14PNV7bxUvr4U7YY0V7Z0Q4m0FHHB5neC/view",
                "https://drive.google.com/file/d/1zcRKvGXWNJ9wxjASlt5zTlGOeemPJQye/view",
                "https://drive.google.com/file/d/10hBNFuxeVhzThvWF1c9hdZ9DImjPe6z2/view",
                "https://drive.google.com/file/d/1SNSXX1PeVivI-kDrWfKkxfy-5vCMOnNT/view",
                "https://drive.google.com/file/d/1HFt2fjs4R8FXz9jPQEnuMa_8NV7XGdD8/view",
                "https://drive.google.com/file/d/1Bh63thXplmhwW2vfTfrghV3bxNs2u63I/view",
                "https://drive.google.com/file/d/1F7cGUOOfsz3-BLjn3qOFdOCDWKAzXdrr/view",
                "https://drive.google.com/file/d/10JiTtSCwQipIB0L_4C4SdHJC70aGfwmo/view",
                "https://drive.google.com/file/d/1lzUp-dbV0YaMStyJGdta3_mmFjZXFJm-/view",
                "https://drive.google.com/file/d/1exT7DDb6Z_I8FwKy2YD_HGbrTH3gQVyL/view",
                "https://drive.google.com/file/d/1oo3TFgVWX0kZoLHb-3N_brnld4laB08M/view",
                "https://drive.google.com/file/d/1R_9QwcN8XFHDcRpJPrCCknHz87cumFs_/view",
                "https://drive.google.com/file/d/1wx8HOzxMjqPlImwpOb7YnzjHDxnLJ1ey/view",
                "https://drive.google.com/file/d/1yY22cX_235W1gsXmUJC0zgIoE0ggqXRD/view",
                "https://drive.google.com/file/d/1NTKLweUeM6uYJ7akQ_n5LAopHKvX_EeF/view",
                "https://drive.google.com/file/d/1INIGeDX5zd84oGsNZSMUnaJeygC4-sCZ/view",
                "https://drive.google.com/file/d/1kpUKNUOAtV1L0Zira-GY28SuVLYlJvuS/view",
                "https://drive.google.com/file/d/1dZ7pqUlhbJqwxEzuvCMEgQQD2hyj3Xha/view",
                "https://drive.google.com/file/d/1Psp_rzI-VKvLcc1ScxrGbf45BlaJArLe/view",
                "https://drive.google.com/file/d/1w62EW81imzwkis4e6G5N6UyPTMGpGhsk/view",
                "https://drive.google.com/file/d/1zXv_sopwXUUCd6fPgGaLjDcwrPT9PrVa/view",
                "https://drive.google.com/file/d/1ZYATiq777zZd1fLQ1kM8ZYLZPptHAJ-v/view",
                "https://drive.google.com/file/d/1WhAdH78xpR2i1mVdHKZMi6g_8Zr-gbgF/view",
                "https://drive.google.com/file/d/1OlPZy9BMBpgzhFD6AZl_72eP-YmFMEY4/view",
                "https://drive.google.com/file/d/1JHjEhBltbfG3ItUhwbcrHHKAxVwlEdiJ/view",
                "https://drive.google.com/file/d/1HhIOoxJ7cRs_-k2nQupIeWKs7xJCmYYF/view",
                "https://drive.google.com/file/d/1ZtYeMSn5zbvfsFWRNVI4XfzY7uTbmlhP/view",
                "https://drive.google.com/file/d/1GnE0TKQaNUTu7DpFfl4XfH0PHhcVAcNk/view",
                "https://drive.google.com/file/d/1eLLUYF7Z9-Df5RMILEGG7JIIdBofTJEb/view",
                "https://drive.google.com/file/d/1muTb2r5D3g8RQb3VV_uVonpM_qRuELEx/view",
                "https://drive.google.com/file/d/1PmnHUcYfnyf4PdXSdjtDOw0h1fk4a5Xq/view",
                "https://drive.google.com/file/d/1d4DWFCV9c2r2LOwdiqV2ae5AA88NonqY/view",
                "https://drive.google.com/file/d/1IEyEjQ35HCm8ebDQYpSKjnsOv5jMqvow/view",
                "https://drive.google.com/file/d/1SajENj9pcQwkV0D-ZFJVhrJr6fY9ps8f/view",
                "https://drive.google.com/file/d/1Rf6yT8i1GB2WO7VPz3pu4bcYSRzEsQox/view",
                "https://drive.google.com/file/d/1fr8Q7cVGT6srrPGssW8iMvcp1YrsuKa3/view",
                "https://drive.google.com/file/d/1_VwfkyxXhCbnkyiEcefP7UKwqeHd8d4E/view",
                "https://drive.google.com/file/d/1Dzimr8C4PhO-EwUUzu0PTifar1jHvRTW/view",
                "https://drive.google.com/file/d/1V87oraI-ls8dSKBnjfZSBS3lTCZlws5g/view",
                "https://drive.google.com/file/d/1a7Z90axum2DZ0dhjtanSa6Di_NNeEHZZ/view",
                "https://drive.google.com/file/d/1YdsBe9VuTNnW8Dze4CRwn7XxNx-xH-3f/view",
                "https://drive.google.com/file/d/1VDnKUs9g1M6EawG79TmTdsX7rMmowvyK/view",
                "https://drive.google.com/file/d/11myWsbHYin22o05hUrU2S0YYSZ45azHf/view",
                "https://drive.google.com/file/d/1m0AXq9COmjm2RWzeLq7J-ZykXG8TEyUO/view",
                "https://drive.google.com/file/d/1s8iRJVaBWJxznHuNfXha4O5yRo_VryE-/view",
                "https://drive.google.com/file/d/1c2xNSvNgTBNonaQ63dy6UnJ0rjMI817f/view",
                "https://drive.google.com/file/d/1rfigjFUX3cihKyd2bnwq7LnrJRPFQX9E/view",
                "https://drive.google.com/file/d/1vfntzLFhBlEFV8xRa1oIHp4IpAN1mWNp/view",
                "https://drive.google.com/file/d/13UBFgBpyUDsl8XzIzzbBcKIyz29cRJoe/view",
                "https://drive.google.com/file/d/12ebNFGIWgLrFkQcUDbteZspqYwZlUARi/view",
                "https://drive.google.com/file/d/1mMLb_C04N4nVsbZ4YBa9NiTIiUWN4DXp/view",
                "https://drive.google.com/file/d/1Jniu6t_YNwpYHokoK3BqXG7A29sTba43/view",
                "https://drive.google.com/file/d/1HVV5EiXgvpSRmSVwFUWKf6naxdz4dWli/view",
                "https://drive.google.com/file/d/1PTGgCGoLe3JS2T5BIiXLCXZzcypsOu6k/view",
                "https://drive.google.com/file/d/1t-LaV9bA2u2KiuMkulVW3X2irqaFccVR/view",
                "https://drive.google.com/file/d/1PI2uG_NJPWKL7Gp98s_4AU8VqnwKD6jw/view",
                "https://drive.google.com/file/d/1edLYZuMiKnbamdu74iDZbqHysds7xwCQ/view",
                "https://drive.google.com/file/d/182pYqjUyGpcBRlDBdg58pWFGBF98jTP-/view",
                "https://drive.google.com/file/d/1tqMyMVv-sa8uggWPJfDLQBG4V7nKuDO7/view",
                "https://drive.google.com/file/d/14DGpHmMDZXQSFQqJeg3MWC00QcS7UK9a/view",
                "https://drive.google.com/file/d/1sr-bOS8flZn86_MUjoGcOKj1IB9IeMqK/view",

                "https://drive.google.com/file/d/1zwEZk_Rlm0frd20hScn36vcoKlw9iG-F/view",
                "https://drive.google.com/file/d/1Lb33iUKHUDHZc8bgWFfwsrkMN5chec9g/view",
                "https://drive.google.com/file/d/164zGtxuNBSGBHWcmmdisn7yvBxbvx9wn/view",
                "https://drive.google.com/file/d/1REfuf0x-b6Y1D_7hOo7FpDLdeza--xN9/view",
                "https://drive.google.com/file/d/197KXiU8QTMfk3mu7ccJv9ytmhoZIrSCB/view",
                "https://drive.google.com/file/d/1kZWHdZwhgZI-yWB2er_aY5kJH7DZC2FB/view",
                "https://drive.google.com/file/d/1rjglagVuIUy0dbI8uO1-341Qm4zuYZvd/view",
                "https://drive.google.com/file/d/1dqEjIvOf90iAqw1OrWUHgeRwe2rsAuv4/view",
                "https://drive.google.com/file/d/1mEkqQVKwRvnjZWzkzj6bhpidPAQuZAaC/view",
                "https://drive.google.com/file/d/1rPv0UQtgf3j0PutWKfS9r-W1XwdIjc2t/view",
                "https://drive.google.com/file/d/1MkCrrEc_uY-VbnBr0BNfW19OxLyA7Hsr/view",
                "https://drive.google.com/file/d/1US_0_sdonJ30EQWI_bc4Tfb2Vgs2dim8/view",
                "https://drive.google.com/file/d/1iiIyY7WqGvu36f54Prk5Ue2ulx4n6HKk/view",
                "https://drive.google.com/file/d/1uBXDwhxV8-LMUTTuYac5feSOB7kSCP8x/view",
                "https://drive.google.com/file/d/1HrVyL-RtZ4Ij2wlLejaTgGZoY7zhaNvp/view",
                "https://drive.google.com/file/d/1jGyw4cIXgLCJAUaGxb6HPMuI2_UmFg9B/view",
                "https://drive.google.com/file/d/1EuRq5kahExgMRwx2vAb4fhs-9RH5A41i/view",
                "https://drive.google.com/file/d/1k44p-n9h5ZHk3cZkQ-JgyzuyBi9pcrwb/view",
                "https://drive.google.com/file/d/1IMs5Do8_-S2warldzgVt_KK_NhzK7cmO/view",
                "https://drive.google.com/file/d/1f2YEVFvLkRHxVGm0n7vYye74h49adF75/view",
                "https://drive.google.com/file/d/14-uWJMrW4EjnDh8AHaYwpPmDUWgC6Px8/view",
                "https://drive.google.com/file/d/1Bmzom8r2jX_52a6z266wF2sr-CF25Zdl/view",
                "https://drive.google.com/file/d/1BNaxOfwCgjeSC7wREuJMnWWXquKZeJfE/view",
                "https://drive.google.com/file/d/1ArMyMXFYpNYLBIGS2mZ1uFtMqofVe3co/view",
                "https://drive.google.com/file/d/1KaAErk7RDvoW7OJIF8L638YS6Sln7CvM/view",
                "https://drive.google.com/file/d/11ZXyKw2-wWMAxPQ2F4s2oyDn7pC1btPT/view",
                "https://drive.google.com/file/d/19BRodyMKrdHuLzO-GoV5gYRll2rn8Yj3/view",
                "https://drive.google.com/file/d/1R5wl4RrBPStaSUkJ3iRa3mR3TwR8_hZE/view",
                "https://drive.google.com/file/d/1e4qFWAvDzCy6PWZh_XVxxuuQyRCVEEc0/view",
                "https://drive.google.com/file/d/1EWZ8xQD4f6j5NKycfZaD3jwkHpI7OSSk/view",
                "https://drive.google.com/file/d/1iT3wKFtBV2CSL8xyTHA0BR7zgyd-z4fK/view",
                "https://drive.google.com/file/d/173v7SPpR9eAmUpztsZ4IN3YUdOC9-m8p/view",
                "https://drive.google.com/file/d/195HrEKKSjrqZpNrBCJoF9JgUmSlx1AcG/view",
                "https://drive.google.com/file/d/1apTzwM55t7sqmDwl6kXTkxTHi2WU3fY5/view",
                "https://drive.google.com/file/d/11yJJX09pX1sk6kfCegw3yu2RA-VnSvzF/view",
                "https://drive.google.com/file/d/1m4WTmCM6Tt_QqzZtyffoITmoJUEBz6UR/view",
                "https://drive.google.com/file/d/1a62kpaoVxzt1vM29gK_xa6cCR4iV1vsm/view",
                "https://drive.google.com/file/d/1mX5KdEdaZb_f6voWpMN2Nf7y7ezVbqw6/view",
                "https://drive.google.com/file/d/18HkV03S9mNFYk5dxxt8tPwn-x3-XMMWx/view",
                "https://drive.google.com/file/d/1H2ibEFhBHQpZw10c5Fc9LOfVbjoVlJrf/view",
                "https://drive.google.com/file/d/1Tp95Q1gQGcFDgrjh80d4Vruzy5otez7U/view",
                "https://drive.google.com/file/d/1lZPfQcx3v7-qiZSW789lpvwevX-56N2K/view",
                "https://drive.google.com/file/d/1mIt-hMPj9qdWI1PI0If5sPacYZI1bYiE/view",
                "https://drive.google.com/file/d/1QXnwOE-GcXiTayAkVv87pXyu_BB07bjr/view",
                "https://drive.google.com/file/d/1OPQlzMqWkBZzO8vuDL3XjVsF2dLUeUFp/view",
                "https://drive.google.com/file/d/1NBf3oqxQZsVh1CBP5eJ_mUNA-K0CTFGI/view",
                "https://drive.google.com/file/d/1Gr1E9Tp0l4bgXKUM9cER6im7SQBT1XIQ/view",
                "https://drive.google.com/file/d/1z4jBCL2_UpKAlM3uv4RHTNHQ61lkOk0F/view",
                "https://drive.google.com/file/d/1lyLKFdIcLjIS_xy6JRCddckn7Y4KuS1X/view",
                "https://drive.google.com/file/d/184lxMCmt0Aoc83lwvxfyQsmb7S_cnfFs/view",
                "https://drive.google.com/file/d/1M0R-7z1VXBeJzb0gKgTJujhGJquLM3fa/view",
                "https://drive.google.com/file/d/1NTBtn7BlbuJSQl_ZuUH62WjipJFnqQQT/view",
                "https://drive.google.com/file/d/19qKqQeqfF-0fULokhjOHWaj7Nt3w1l4O/view",
                "https://drive.google.com/file/d/1MIsaz2_JLGogZRtT7UvPW1MDk_lH2elw/view",
                "https://drive.google.com/file/d/1H0-rOAI70-PjrUGMhIZPWVPGXFyRDyYY/view",
                "https://drive.google.com/file/d/1029SifRubc6I6K71NRkNIJ5NTmmlny7N/view",
                "https://drive.google.com/file/d/12xHvLY7IgpA2zOwtVvxe_ncV3fS4pqeU/view",
                "https://drive.google.com/file/d/188DCHFwa1ltKlFilMAgG31oG-OtBBpP6/view",
                "https://drive.google.com/file/d/1Ve1zKrrNWVDzw7mbxx-7Tqwb63Na8qBr/view",
                "https://drive.google.com/file/d/134trpQRWVUet7RCLtR2JEwYxnk2hRtDF/view",
                "https://drive.google.com/file/d/1Z8pOqy2TMajChLZvRtzM5WdDvtx_STln/view",
                "https://drive.google.com/file/d/1kra3FSYo2N63dahrniC_h-OcsvLV06rg/view",
                "https://drive.google.com/file/d/1YbAB0aFkt3Czvjk1Ctn5apRxjQAKPCOj/view",
                "https://drive.google.com/file/d/1dsdJiaJB9hOlPROj-3JjNU1XEBncuE-M/view",
                "https://drive.google.com/file/d/1vcxrKFB7ugz0_Ao5WjpLpGVnUM2fqvZq/view",
                "https://drive.google.com/file/d/13F4-U1MCE3B9SsF9mdAuAQC5zTvz7UHh/view",
                "https://drive.google.com/file/d/15C0FJICMwcGXaC9rHZ-Nv6keqG6FkRSi/view",
                "https://drive.google.com/file/d/1SjGSMue8KJkkAftm2Q41Krr2KiKSQCXM/view",
                "https://drive.google.com/file/d/1sy6HnaM993PhjwY2n2o1TlQ6dU0j_t8B/view",
                "https://drive.google.com/file/d/1xEbS9JZk9Yq24x41UO8P7HZvLHxG5CC4/view",
                "https://drive.google.com/file/d/18wuOKBCxG81mxxQt6CRwjZYwwiOM5Ytf/view",
                "https://drive.google.com/file/d/1NCskfxyqGW5w0MdXyp3oH-jC-UkGB_1J/view",
                "https://drive.google.com/file/d/1TN0TBu5yDMjk0JuZbsNDt2pyz9m2FAJa/view",
                "https://drive.google.com/file/d/1rPP2EEwaWYvzAQAD1ky6WrnAScPyhgnt/view",
                "https://drive.google.com/file/d/1sBDXnmEGEGVqJuFMbCi77mBk1cKMkZKy/view",
                "https://drive.google.com/file/d/1nem8jPnvFS3tJsJ3R8xqvdpZPEw0weJs/view",
                "https://drive.google.com/file/d/1nxU5bqg51oPhU9To9suH7TsWPO6sOnHv/view",
                "https://drive.google.com/file/d/1Vw27cGyZANgK3vmWWAzvxd_tBuN0Z2i-/view",
                "https://drive.google.com/file/d/1FauBzuWIEuYx12_e2QKnxMVNNYgX-UUZ/view",
                "https://drive.google.com/file/d/15UERUSaCqy_F56xpeZiJ1s0XNubyxMBL/view",
                "https://drive.google.com/file/d/1HH21JNlhIhAUCniKSfm90yRP_VjziGou/view",
                "https://drive.google.com/file/d/1gTctZ0wlf065Sm1_cpknYQ0f-3eQQ0j2/view",
                "https://drive.google.com/file/d/1UfQIFgNq4UN89G9CgQPoz66PdsUSqc0h/view",
                "https://drive.google.com/file/d/14y3nZaszWUi_o7M4ByH2sY5QVhh2P4yZ/view",
                "https://drive.google.com/file/d/1wfE8kce1Ukuragbl827YZSEUauEbJM9g/view",
                "https://drive.google.com/file/d/1LKIrxWmHGJpQpUnoezxLWqPVUXNpVeV_/view",
                "https://drive.google.com/file/d/1uSlYsUePXDUT70utwWI71rYvbwQ3dBi0/view",
                "https://drive.google.com/file/d/1rM0Tx9W_lWYpOIoQ8qJxU5fa2ANY5jGw/view",
                "https://drive.google.com/file/d/1z6Fz8B2MXIJvgGX2CADUkFlh0_0kuKC4/view",
                "https://drive.google.com/file/d/1jOl06Qtolw8iTAf68SwDA0TwckZtjDaf/view",
                "https://drive.google.com/file/d/1-unYhY19oPLxrMLkV2CQAOcpsPf0a_Ef/view",
                "https://drive.google.com/file/d/1BACQo18VMTg3Xqy3omLo87Qrj5N-TP4n/view",
                "https://drive.google.com/file/d/1AJ9tEgFCml8d85IOBdT-AKvGb4YjL7bl/view",
                "https://drive.google.com/file/d/1fuRPlK3gAViNnWE1wvry1goL4enxjefN/view",
                "https://drive.google.com/file/d/19iFZB9GFe5Mw3l4KEt4QxMEtrTaxCEy4/view",
                "https://drive.google.com/file/d/1Kr1orDM3EvQjaylH6SKR2e731bkSFGJf/view",
                "https://drive.google.com/file/d/1IVBcYlwrZrJFB6c92EfUSRIYhtfFBn8N/view",
                "https://drive.google.com/file/d/1PWzG18YvOIKvNrhIkVriaPO3QqKrdr0g/view",
                "https://drive.google.com/file/d/17_HgFMc_dRSdOm29xf4IydCKMu81CH01/view",
                "https://drive.google.com/file/d/10rxHTGc6yF2ocKu1HwkzLLoNvkQ4U0V_/view",

                "https://drive.google.com/file/d/186DA5LX6LynPTgM0XNGmG2ugr5kOi2y8/view",
                "https://drive.google.com/file/d/1-IUjOTxY_TtgHz0S5P4j-N0jmJeXGYqy/view",
                "https://drive.google.com/file/d/1cmejbKY5v5TEk4oqG81TRGeZPQcaEnuo/view",
                "https://drive.google.com/file/d/1gf1wxw5V65S3TZFK7bqYae5EDfJMJlb-/view",
                "https://drive.google.com/file/d/1UK7AVv4ypFR804jRsgKMAB32U_5CdOLx/view",
                "https://drive.google.com/file/d/10KcQagOBGz4J5GL73dDsIi9nWGMy0KxS/view",
                "https://drive.google.com/file/d/1EFPfSJ2ABZOQ8s_6bEytDZEU_TLfNWak/view",
                "https://drive.google.com/file/d/1Fwc7d507xnFuJZ3fxGLJ3Vrs5Puz8LjR/view",
                "https://drive.google.com/file/d/1PwM7glc5t8BS-5SKxZJws-JKIN9zQuoT/view",
                "https://drive.google.com/file/d/1xKIFmWoAbob97zMi8kDAay4G4LeDbBJN/view",
                "https://drive.google.com/file/d/1Y2sPN9Fsqh1XKUq9p004vhPxh-MFAL3f/view",
                "https://drive.google.com/file/d/11RjO6Jn0O58eTWN9bi1zFLu7pP42j_u0/view",
                "https://drive.google.com/file/d/11lkW1IVnS3D-1p__J8aRZ2bGGPR9iUED/view",
                "https://drive.google.com/file/d/18fNYnuAEkIT6U04ZWfCVqVyH7-hkw0pU/view",
                "https://drive.google.com/file/d/1P0UBSbvQ7PtyomX4GpiFmpNpZ7qnBGc1/view",
                "https://drive.google.com/file/d/1n4_-lwcf2RAOTRfKeZOfHHTWLUlsU63D/view",
                "https://drive.google.com/file/d/1KzgdRDF9udGMKr20Y7ycK3NzIO9oyAe1/view",
                "https://drive.google.com/file/d/1pL_pDT4lxQEkrFoGZcW6f_k8Ds9BvZwo/view",
                "https://drive.google.com/file/d/19IzqfqwK8ot7aFLa8CfgADD6fRl2IsAz/view",
                "https://drive.google.com/file/d/1_u01MY0aFhXzXTfOWTbvXHyMTFT85PVi/view",
                "https://drive.google.com/file/d/139BZ-fD8_jTJj18svprzyMp0sB8nZomb/view",
                "https://drive.google.com/file/d/1MvMxB7ICgU9PIW8XIMzqXY3AarWH6MnK/view",
                "https://drive.google.com/file/d/1mf0WgMi2ux3HF1CnGpLeeiNvGZ70I9LT/view",
                "https://drive.google.com/file/d/1X4F_pgl8Fg-nlg6ijOAnX9b1I2IgTgAI/view",
                "https://drive.google.com/file/d/1SwcnwhfsZM_o7rsBDv7FJkuA_fqWngeM/view",
                "https://drive.google.com/file/d/1_FsU2-DJoT5TURVNyoaQZt77DQaRUfiv/view",
                "https://drive.google.com/file/d/1uAFdtcrOCVFuGwkNJM-neSwwPO8i4sDM/view",
                "https://drive.google.com/file/d/1WC64UzujgQ3-9UtDIPWKEg_5ISFQzNoN/view",
                "https://drive.google.com/file/d/1iT6TFmUFKGdGzygO2mc4T9Q7_HJf1mq-/view",
                "https://drive.google.com/file/d/1PN6LbqMdwZA1mnE1IFXl0S47KN9wehFM/view",
                "https://drive.google.com/file/d/11Q8dKr_BmSizT6-WITWeugnpoki6-CyK/view",
                "https://drive.google.com/file/d/1TWTi9ZtlkfbBzBrBEt9hU7LODCBpuN6r/view",
                "https://drive.google.com/file/d/1sQs01FGnpn8Kz3wPaGjZLafhaWcuiK2s/view",
                "https://drive.google.com/file/d/1keRD-Nog_kygV8ZX9oPUQfrY_eMpgwR0/view",
                "https://drive.google.com/file/d/1HCNzAc9tDlHG84US7Sd2WSoPLWW_-vlh/view",
                "https://drive.google.com/file/d/1HVrxWBP_8Ae5IbHzwgKG7WlpXN8pUd7e/view",
                "https://drive.google.com/file/d/1xKkXCwQwPk9WHj9J5RDnkxt6mob0sy-k/view",
                "https://drive.google.com/file/d/1lxWvK00_57-1R13cYErgUojA6RF-iozH/view",
                "https://drive.google.com/file/d/19LH4XEjKZDNYaWtl4dkuRn_vMByuSdOr/view",
                "https://drive.google.com/file/d/1_rfdPZUpV6vlASWFmaKjx_wVoTjPH1gA/view",
                "https://drive.google.com/file/d/1gbSD2MBbS5feHt9niPGgkzv6Evvp395e/view",
                "https://drive.google.com/file/d/1TgABGiovFlwlJuaKHsmaKUb7sPAHx2_n/view",
                "https://drive.google.com/file/d/1xA6rPiqt1dfK96JvIvig6IZDBcBlP2la/view",
                "https://drive.google.com/file/d/1AwNJeXv6J5G8mOhAYkB_PiZjyuWyZFNd/view",
                "https://drive.google.com/file/d/1Mdp-E-Ip1KlMSyqUbHf-shfQTqDcjJp4/view",
                "https://drive.google.com/file/d/1n8TrjZTThQ_y-ZjyJO7VJHyOOLxnYeuM/view",
                "https://drive.google.com/file/d/1eUspc3GDFCyp_LqlvR9XQxPgN_cZd1Gi/view",
                "https://drive.google.com/file/d/1araM-Re0m05WsYz0xVtFg1fi_vbsgjIz/view",
                "https://drive.google.com/file/d/11l5pL8VCiM-GMFb1PsYlfFgaj9_ck2tj/view",
                "https://drive.google.com/file/d/1l06FFvt8pyih6boPK9K68hsKbJ-awW6n/view",
                "https://drive.google.com/file/d/1cJJA41o2UtLLw__oj9_beb5R07Z2pPrF/view",
                "https://drive.google.com/file/d/1KG1SXVpQmbcrJJQ28j0G1Xc8Te5ghm41/view",
                "https://drive.google.com/file/d/1kC3LluXYWIBushQkQ-0ns6FVs2B7ascv/view",
                "https://drive.google.com/file/d/1IAvVEFZnRXvp9-u8ftAfV24vbCg04Qcx/view",
                "https://drive.google.com/file/d/1yhVM4jZj_yTDfIxXJFqlC8TDj_-iGeMC/view",
                "https://drive.google.com/file/d/1vSjCMLrocJDo_LXbsNzaY4SZG2-uzMC4/view",
                "https://drive.google.com/file/d/1rJnjcdShdJ83o0qmykQnXAeLAHSBlji-/view",
                "https://drive.google.com/file/d/1S9XU_5yVECNk9omiLiyqIGQOhObohdiJ/view",
                "https://drive.google.com/file/d/1RNAe6tmIfEnD3_CrNyC5W2Av_zIv2aQ6/view",
                "https://drive.google.com/file/d/1gQdWT6rtOK0ors8sXnMuJw3aK1ig0GxL/view",
                "https://drive.google.com/file/d/17A0Wf8bt756jGQvQKt8CCAMkz0HK3YCI/view",
                "https://drive.google.com/file/d/1nEdr0T3ts1mqbN3LU2izD_TPvHnjGlav/view",
                "https://drive.google.com/file/d/1TFHXwtrSnVOxUyJeDgEEgW8yKnPvlQbo/view",
                "https://drive.google.com/file/d/197mguR9ZckzBkHXdPNTOUKPMIbmtNw25/view",
                "https://drive.google.com/file/d/1dcLXCNPg4qHPyti7tRWIsYzDUZWYExVC/view",
                "https://drive.google.com/file/d/1RL5TPoXpX5lSvlAS242WWKXKTJZ7oCjj/view",
                "https://drive.google.com/file/d/1hEZBgPiUsaRzuNwOBdrc3N0MBWmey8_s/view",
                "https://drive.google.com/file/d/1W4vgQc_En-FcHDv-A2AXnNoTaGpD0YBs/view",
                "https://drive.google.com/file/d/12lFWXr9MxYMMuRUGUzkxCDXhSjQdU6qu/view",
                "https://drive.google.com/file/d/1-CXYAjt0wlK4bx_NNTrRW25KMkL9sVoW/view",
                "https://drive.google.com/file/d/1FYghi2svqoaPWUPfwjxMZiCrD4sRuZD5/view",
                "https://drive.google.com/file/d/1i5spwx8CS-4pyZzTSFloLzimdDyiSSLf/view",
                "https://drive.google.com/file/d/1CmkwTsvCyxVi16SsS1XU-85gDzztkVQF/view",
                "https://drive.google.com/file/d/1eOgqG6P0BFx7Vkovy6iQre8ClMU-h4v9/view",
                "https://drive.google.com/file/d/1QFdstPerNNhrsMU2PaQvbi_JEQWB8ssX/view",
                "https://drive.google.com/file/d/16YbnwCvS5NYHrZtVoKBaExyAG37_VUS2/view",
                "https://drive.google.com/file/d/16DY-EDiFTvql0p7qU1ein8SRcIvKyucF/view",
                "https://drive.google.com/file/d/1BC3EAxqf-u28BTOYEDvAO5u3QkOhpzrH/view",
                "https://drive.google.com/file/d/1dHvA2Gz4_NsWOTKeFXYQMi_MNEpOi8UN/view",
                "https://drive.google.com/file/d/1mfinIJ1N284Q20wwYxY_xetog8qay_Wg/view",
                "https://drive.google.com/file/d/14T7l03HeN5_Jt329LuiYQALhkTj9T2Dc/view",
                "https://drive.google.com/file/d/1ZIGyVVGTNlBPv2UQ7VdcXyTeawoO4ba2/view",
                "https://drive.google.com/file/d/1UM60Fz7jBBoJEN8XLhv6NHj8IPk-xbkI/view",
                "https://drive.google.com/file/d/1c5LIuSGmc5N3n_mb1MXpJJ4clAmtzWV9/view",
                "https://drive.google.com/file/d/1j3xSBCBf0vEaeGdlNCb8CCdffm_eeEgb/view",
                "https://drive.google.com/file/d/1aF1BGO_atIq7kdbj5MaR8ze6dK6pbvqZ/view",
                "https://drive.google.com/file/d/10j-hx0vB3BvG47VP8k_XT7BENTzjmPMr/view",
                "https://drive.google.com/file/d/1aBZYtUD74vDUedOUgbft7InyTsrkT-_-/view",
                "https://drive.google.com/file/d/1AgXZ2fl7oUuCngFg-_4pCCS1XCzPhuMW/view",
                "https://drive.google.com/file/d/10E8FEAqBjSn4XzWeUkX0H3f7r17Xvp5P/view",
                "https://drive.google.com/file/d/1NzOKSlvlrppqQIyJQG45cAtU6Hpa8g0m/view",
                "https://drive.google.com/file/d/1t5t1X5LNH-5H_ge_Yxo2lpEK729mckw2/view",
                "https://drive.google.com/file/d/1DR_cN3iUp3VqUYmttbXbDhi2zeq1tiKJ/view",
                "https://drive.google.com/file/d/1DkK_xkX4rqdboNEF_uwa3Ed1AcGfYtCf/view",
                "https://drive.google.com/file/d/1akCpdp6n6NXJ_yaUaQk3eyOlv8-S_Uq2/view",
                "https://drive.google.com/file/d/1bkUJyjxbr1Xm3xAVR6picepNiXJ2Y7e5/view",
                "https://drive.google.com/file/d/1w-odtQg7CrJfI5vyimcKHdFDJeg42WPg/view",
                "https://drive.google.com/file/d/1aOg5GWtbMbb8hRCNbXE_PK-Ii5vPE5Do/view",
                "https://drive.google.com/file/d/1pXJm1z98RzFn2T8s6lG8lWvXNAFxDPP6/view",
                "https://drive.google.com/file/d/1WQFEDx0orEzNTQk4Ju6rTQGlzMFeRhLR/view",

                "https://drive.google.com/file/d/1sXdbK-wqvtx6C1Ge-qize4vcXYw10eaJ/view",
                "https://drive.google.com/file/d/1CuO_Hmmd1HfjSmZUqzE36dQBzqyfCeWV/view",
                "https://drive.google.com/file/d/1dYW-lxgjXelbcc029ODGnSE9ZQOLsGvf/view",
                "https://drive.google.com/file/d/1cf2sX-K20Rw9SdCJJApy0eH2Robg3yO6/view",
                "https://drive.google.com/file/d/1v3K5bbzaWjBCmly_I2HHxPf1a4CkCayq/view",
                "https://drive.google.com/file/d/1yxNT5Q6ylgr5E2hGTNEiNKCf4ohuM-Ax/view",
                "https://drive.google.com/file/d/1OHMWW81mhU5BMupYWCjpjOqzpLh4Q7yD/view",
                "https://drive.google.com/file/d/1XbE9rtPROPHxNDAuze7sHHaFmSmrGHBg/view",
                "https://drive.google.com/file/d/1LJMgoKo4MuKRJ-VRxXdLXm3zmrueg4tY/view",
                "https://drive.google.com/file/d/1qUvzsrP7gsXTIDfdhYRfB4crB2vlGaUC/view",
                "https://drive.google.com/file/d/1BvEcO5J24M-r-SwUA3gGknIw3SZfqfHN/view",
                "https://drive.google.com/file/d/11d4O80j0GseYt4Uv4gKD9VycTC3AM-Vn/view",
                "https://drive.google.com/file/d/1O7njK0MrR8TtlzvhEzf4SRHWxthcSiER/view",
                "https://drive.google.com/file/d/13fliACRHSDxBrMZAwLVwzYSgXTS5yZt3/view",
                "https://drive.google.com/file/d/1nHtLMcLJ4rhMn0PPx3-Q1DrPvjcpbfK0/view",
                "https://drive.google.com/file/d/1F4VcjzJxyUJRIwUW8bC2OeshSvku5-AS/view",
                "https://drive.google.com/file/d/17E_YKuuKcOg9Kyx6nLxCW5kwud5gab7r/view",
                "https://drive.google.com/file/d/1lrdoFLYVIDZ0G48oyyyzGRjBudW8_B9s/view",
                "https://drive.google.com/file/d/1o14NciNI3Kk3iJfka9nAjyWRo9LiTHmN/view",
                "https://drive.google.com/file/d/1gP4AcbN3nlFqI3zPC19r1cGiIHsx-oRj/view",
                "https://drive.google.com/file/d/1xSBzw4aFiP3tT5mD3GD_NGQB3ancJ4kb/view",
                "https://drive.google.com/file/d/1I1tlvpx7wU-QnfTTqt_4ACLYb6P7u2VT/view",
                "https://drive.google.com/file/d/1NGAfABvohrbcQj7ZqJdz6tgLb1utmndv/view",
                "https://drive.google.com/file/d/1R1dAM2Ean4jHrla_wWiiuD10rEZHS_Or/view",
                "https://drive.google.com/file/d/1FZzMT9xJo2flvV3G6TxgXy2ELfvIU2yl/view",
                "https://drive.google.com/file/d/1mlsh_CzvDMwHYnMmFpH4_NzrTjLVT9wF/view",
                "https://drive.google.com/file/d/1Jm57AWs_rpUHDY4KxdeCWDdPWa8tpR8m/view",
                "https://drive.google.com/file/d/1c8LbhRevuNuBmzwnvT1r4wV1RBcLeAor/view",
                "https://drive.google.com/file/d/1zAQsbc4S0yC98b1Oslqw4aJJx0UCxxnh/view",
                "https://drive.google.com/file/d/1Eu4Q8QPoyhtYNyvRQyi16znOpKBgm6EI/view",
                "https://drive.google.com/file/d/1FBySgCDxB4LkddNYKhJ-A9O1Vqmxmluf/view",
                "https://drive.google.com/file/d/1INwMrS67IUVTh1bQMn0l5FSlYE6K6xrb/view",
                "https://drive.google.com/file/d/1EQs6Zh-vPj_e5vFkno_m-kVAQCFF6O_q/view",
                "https://drive.google.com/file/d/1b6K0qSTvehdZY0WmTZ411H2l_li7quFJ/view",
                "https://drive.google.com/file/d/1ard2qOqEZmefBlvMC8eqStmK_25OV1i4/view",
                "https://drive.google.com/file/d/1gAFtNPlg9fITD79ZV5mboKD28kcN-phs/view",
                "https://drive.google.com/file/d/1zSSVcxTDEamOrEE1_7p1_wHiS6cdiwor/view",
                "https://drive.google.com/file/d/11h_vRnMVdtHgaAMo3x7zmPgNPHXy77rv/view",
                "https://drive.google.com/file/d/12hLTSNLQLhkf0Hn_V5CzxbrqmPottGP4/view",
                "https://drive.google.com/file/d/1Mg1HR_HWxyDGxzl5lB7Z0rDX4bModMgf/view"



        };

        // Adapter para el spinner
        videosAdapter = new ArrayAdapter<>(this, android.R.layout.simple_spinner_item, videoNames);
        videosAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        spinnerVideos.setAdapter(videosAdapter);

        // Random
        random = new Random();


        spinnerVideos.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                if (position > 0 && position < videoUrls.length) {
                    String selectedVideoUrl = videoUrls[position];
                    if (selectedVideoUrl != null && !selectedVideoUrl.isEmpty()) {
                        openWeb(selectedVideoUrl);
                    }
                }
            }
            @Override
            public void onNothingSelected(AdapterView<?> parent) { /* no-op */ }
        });

        // Botón Aleatorio (evita el índice 0)
        playRandomButton.setOnClickListener(v -> {
            int randomIndex = random.nextInt(videoUrls.length - 1) + 1;
            String randomVideoUrl = videoUrls[randomIndex];
            if (randomVideoUrl != null && !randomVideoUrl.isEmpty()) {
                openWeb(randomVideoUrl);
            }
        });
    }

    // Abre SIEMPRE WebViewActivityGeneral con la clave "url"
    private void openWeb(String url) {
        Intent intent = new Intent(novelas1.this, WebViewActivityGeneral.class);
        intent.putExtra("url", url);
        startActivity(intent);
    }
}
