name: Build and Commit APK (unsigned)

on:
  push:
    branches: [ master ]     # ajusta si usas main
    paths-ignore:
      - "apk/**"             # evita loop al commitear el APK
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODULE_PATH: app       # ajusta si tu módulo no es 'app'
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "17" }
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x ./gradlew
      - name: Build APK
        run: ./gradlew :$MODULE_PATH:assembleDebug --stacktrace
      - name: Copy APK
        run: |
          mkdir -p apk/debug
          cp $MODULE_PATH/build/outputs/apk/debug/*.apk apk/debug/app-debug.apk
      - name: Commit APK back
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add apk/debug/app-debug.apk
          if ! git diff --cached --quiet; then
            git commit -m "CI: update debug APK [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
